'use strict';
const $=id=>document.getElementById(id), canvas=$('canvas'),ctx=canvas.getContext('2d');
const starts=[0,60,145,195,280,335,440,525,620],ends=[60,145,195,280,335,440,525,620,720],titles=['Meet the food protein','Sequence determines shape','Shape determines function','Digestion dismantles the protein','Absorption and transport','DNA selects the new protein','Ribosomes build a new protein','Why swallowed insulin is different','Other fates and recap'];
const sentences=NARRATION.map(s=>s.match(/[^.!?]+[.!?]+(?:[”’])?/g)||[s]);
const steps=[0,15,29,42,60,78,100,122,145,161,180,195,210,229,249,268,274,280,290,309,323,335,352,377,406,429,440,457,482,510,525,546,566,584,604,620,642,664,688,705];
const recorded=new Map();let audioFailed=new Set();
let t=0,playing=false,last=0,chapter=0,captionIndex=-1,narrationKey='',pausedAt=null;const passed=new Set();let speed=Number($('speed').value);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');$('motion').checked=reduced.matches;
const anatomy=new Image();anatomy.src='assets/digestion.png';
const residues=MOLECULE.filter(a=>a.name==='CA');const byRes=new Map();MOLECULE.forEach(a=>{if(!byRes.has(a.i))byRes.set(a.i,[]);byRes.get(a.i).push(a)});
const colors={LYS:'#4278e6',GLU:'#e36883',PHE:'#e2a436',SER:'#12a391',ARG:'#4278e6',ASP:'#e36883',LEU:'#e2a436',VAL:'#e2a436',ILE:'#e2a436',ALA:'#e2a436',ASN:'#12a391',GLN:'#12a391',THR:'#12a391'};
const ease=x=>{x=Math.max(0,Math.min(1,x));return x*x*(3-2*x)},mix=(a,b,p)=>a+(b-a)*p;
function sceneAt(v){return Math.min(8,ends.findIndex(e=>v<e)<0?8:ends.findIndex(e=>v<e))}
function time(v){return Math.floor(v/60)+':'+String(Math.floor(v%60)).padStart(2,'0')}
function cancelVoice(){if('speechSynthesis'in window)speechSynthesis.cancel();narrationKey=''; if(window.instructorAudio){window.instructorAudio.pause();window.instructorAudio=null}}
function voice(text,key){if(window.INSTRUCTOR_AUDIO?.[chapter]&&!audioFailed.has(chapter)&&$('voice').checked&&playing){let a=recorded.get(chapter);if(!a){a=new Audio(window.INSTRUCTOR_AUDIO[chapter]);recorded.set(chapter,a);a.onerror=()=>{audioFailed.add(chapter);$('voiceStatus').textContent='(recording unavailable; browser voice)';narrationKey=''};}if(window.instructorAudio!==a){cancelVoice();window.instructorAudio=a;a.currentTime=t-starts[chapter];a.playbackRate=speed;a.play().catch(()=>audioFailed.add(chapter));}return;}if(!$('voice').checked||!playing||key===narrationKey)return;cancelVoice();narrationKey=key;if('speechSynthesis'in window){let u=new SpeechSynthesisUtterance(text);u.rate=speed;u.lang='en-US';u.onstart=()=>{$('status').textContent='Narration playing · '+titles[chapter]};u.onerror=()=>{$('status').textContent='Browser narration is unavailable. Captions and transcript remain available.'};speechSynthesis.speak(u)}}
function pause(){playing=false;cancelVoice();update()}
function play(){if(t>=720)seek(0);if(pausedAt!==null){passed.add(pausedAt);pausedAt=null;$('prediction').hidden=true}playing=true;last=performance.now();update()}
function seek(v){cancelVoice();t=Math.max(0,Math.min(720,v));pausedAt=null;$('prediction').hidden=true;captionIndex=-1;chapter=sceneAt(t);update();draw()}
function showPrediction(at){t=at;pause();pausedAt=at;$('prediction').hidden=false;$('answer').hidden=true;$('reveal').hidden=false;$('question').textContent=at===180?'Why could one changed amino acid affect function?':at===274?'Is the original protein still intact after digestion?':'What determines the amino-acid order of insulin produced by a person’s pancreas?';$('answer').textContent=at===180?'Side-chain properties can change folding, surface interactions, or binding. A substitution does not always change the whole fold or impair function.':at===604?'The beta cell’s INS gene, through transcription and translation, specifies insulin’s amino-acid order. Food supplies building materials, not the sequence instructions.':'No. Dietary proteins are generally hydrolyzed into small peptides and free amino acids. These materials retain their identity; the original intact food protein does not.';$('reveal').focus();update()}
const descriptions=[
'A rotating, folded egg-white lysozyme is followed into a close view of its amino-acid chain. Backbone atoms and peptide C–N links are revealed. Residue boundaries identify two linked residues as a dipeptide and three as a tripeptide. The enlarged chain is a conceptual view of the same sequence.',
'The same residues keep their colors. A close chemical view distinguishes lysine’s positively charged nitrogen-containing side chain, glutamate’s negatively charged carboxyl group, phenylalanine’s nonpolar aromatic ring, and serine’s polar hydroxyl group. The chain compacts conceptually toward the experimental fold. Nonpolar groups tend to be buried; opposite charges can attract, like charges can repel, and polar groups can form hydrogen bonds.',
'The same folded lysozyme has a substrate-binding cleft. A schematic sugar-chain fragment moves toward that cleft. A local hypothetical alteration displaces its binding position; the fragment moves away. The effect is conceptual, not an experimentally predicted mutation. Sickle hemoglobin is a distinct example of changed surface interactions under low oxygen.',
'The tracked food protein travels into an anatomical stomach illustration. An enlarged molecular view remains connected to the organ by a leader line. Acid loosens its shape without breaking peptide bonds. Gold protease models approach; selected peptide C–N bonds disappear and colored chain fragments separate. The camera tracks toward the duodenum and pancreatic region; further hydrolysis gives small peptides and free amino acids. The camera continues toward the intestinal brush border for absorption.'
];
const explanations=[
'Each amino acid contributes to a repeating nitrogen-containing peptide backbone. A peptide bond joins the carbonyl carbon of one residue to the amino nitrogen of the next. Side chains extend from the alpha carbon. A protein has a specific sequence, not a random mixture. Our tracked example is lysozyme, a protein in egg white.',
'Water, side-chain chemistry, and the surrounding conditions influence folding. Hydrophobic grouping, charge attraction and repulsion, and hydrogen bonding help explain interactions. The transition here is a conceptual morph toward the known native structure, not a physical folding simulation. Disulfide links also stabilize lysozyme; acid does not necessarily break them.',
'Lysozyme recognizes sugar chains in bacterial cell walls. Binding depends on both shape and chemical interactions. The animated substrate fragment and local alteration are illustrative, not a docking calculation or a named mutation. In sickle cell disease, a hemoglobin substitution promotes interactions between molecules under low oxygen; it is not the same as this enzyme example.',
'Acid disrupts higher-order structure; it does not perform peptide-bond hydrolysis in this illustration. Pepsin begins proteolysis in the stomach. Pancreatic proteases act in the small-intestinal lumen; intestinal peptidases continue breakdown. Lysozyme can resist unfolding and digestion because of its compact disulfide-stabilized structure, so this is a general dietary-protein teaching model rather than a measured kinetic account for lysozyme.'
];
descriptions.push(...EXT_DESCRIPTIONS);explanations.push(...EXT_EXPLANATIONS);
$('chapters').innerHTML=titles.map((s,i)=>`<button data-scene="${i}" aria-current="${i===0}">${String(i+1).padStart(2,'0')} · ${s}</button>`).join('');
$('chapters').addEventListener('click',e=>{let b=e.target.closest('button');if(b)seek(starts[+b.dataset.scene])});
$('transcriptText').innerHTML=titles.map((s,i)=>`<h3>${i+1}. ${s} <small>(${time(starts[i])}–${time(ends[i])})</small></h3><p>${NARRATION[i]}</p><p class="description"><strong>Visual description:</strong> ${descriptions[i]}</p>`).join('');
function update(){chapter=sceneAt(t);$('chapter').textContent=`0${chapter+1} / 09 · ${['STRUCTURE','FOLDING','FUNCTION','DIGESTION','ABSORPTION','GENE EXPRESSION','TRANSLATION','PROTEIN HORMONES','METABOLIC FATES'][chapter]}`;$('title').textContent=titles[chapter];$('play').textContent=playing?'Pause':'Play';$('clock').textContent=time(t);$('seek').value=t;document.querySelectorAll('[data-scene]').forEach(b=>b.setAttribute('aria-current',String(+b.dataset.scene===chapter)));$('prev').disabled=t===0;$('next').disabled=t>=720;$('explanation').textContent=explanations[chapter];canvas.setAttribute('aria-label',descriptions[chapter]);
let p=(t-starts[chapter])/(ends[chapter]-starts[chapter]);let weights=sentences[chapter].map(s=>s.trim().split(/\s+/).length);let total=weights.reduce((a,b)=>a+b,0),acc=0,idx=weights.length-1;for(let j=0;j<weights.length;j++){acc+=weights[j];if(p<acc/total){idx=j;break}}
if(idx!==captionIndex||$('caption').dataset.scene!==String(chapter)){captionIndex=idx;$('caption').dataset.scene=chapter;$('caption').textContent=sentences[chapter][idx].trim();}
voice(sentences[chapter][idx].trim(),chapter+'-'+idx);if(playing&& !$('voice').checked)$('status').textContent='Playing · '+titles[chapter];else if(!playing&&pausedAt===null&&t<720)$('status').textContent='Paused · '+time(t)+' · '+titles[chapter];
if(t>=720&&!playing)$('status').textContent='Journey complete. Food supplies the amino acids; DNA supplies the instructions.';
$('location').textContent=chapter>=4?EXT_LOCATIONS[chapter-4]:chapter<3?'TRACKED FOOD PROTEIN · EGG-WHITE LYSOZYME':t<242?'STOMACH · ACID + PEPSIN':'SMALL INTESTINE · PROTEASES';$('modelNote').textContent=chapter>=4?EXT_NOTES[chapter-4]:chapter===0&&t<15?'Experimental structure · PDB 1LYZ':'Conceptual motion · same tracked sequence';
}
$('play').onclick=()=>playing?pause():play();$('prev').onclick=()=>seek([...steps].reverse().find(v=>v<t-1)||0);$('next').onclick=()=>{let v=steps.find(v=>v>t+1)??720;if([180,274,604].includes(v)&&!passed.has(v))showPrediction(v);else seek(v)};$('replay').onclick=()=>{let v=[...steps].reverse().find(v=>v<=t)||0;for(let at of [180,274,604])if(at>=v)passed.delete(at);seek(v)};
$('seek').oninput=e=>seek(+e.target.value);$('speed').onchange=e=>{speed=+e.target.value;cancelVoice()};$('cc').onclick=()=>{let on=$('cc').getAttribute('aria-pressed')!=='true';$('cc').setAttribute('aria-pressed',on);$('cc').textContent=on?'Captions on':'Captions off';$('caption').hidden=!on};$('transcriptBtn').onclick=()=>{let hidden=!$('transcript').hidden;$('transcript').hidden=hidden;$('transcriptBtn').setAttribute('aria-expanded',!hidden)};$('explain').onclick=()=>{let hidden=!$('explanation').hidden;$('explanation').hidden=hidden;$('explain').setAttribute('aria-expanded',!hidden)};$('reveal').onclick=()=>{$('answer').hidden=false;$('reveal').hidden=true};$('continue').onclick=()=>{passed.add(pausedAt);pausedAt=null;$('prediction').hidden=true;$('play').focus();play()};$('voice').onchange=()=>{cancelVoice();if(!$('voice').checked)$('status').textContent='Narration off. Synchronized captions remain available.'};$('motion').onchange=draw;
if(!('speechSynthesis'in window)){$('voice').disabled=true;$('voiceStatus').textContent='unavailable; use captions'}
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();playing?pause():play()}if(e.key==='ArrowRight'){e.preventDefault();$('next').click()}if(e.key==='ArrowLeft'){e.preventDefault();$('prev').click()}});
function line(a,b,color,width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}
function label(text,x,y,color='#24475f',size=21){size=size/Math.min(1,Math.abs(ctx.getTransform().a));ctx.fillStyle=color;ctx.font=`${size}px Arial`;ctx.textAlign='center';ctx.save();ctx.shadowColor='#fff';ctx.shadowBlur=0;if(chapter>=4){ctx.strokeStyle='#ffffffee';ctx.lineWidth=4;ctx.lineJoin='round';ctx.strokeText(text,x,y)}ctx.fillText(text,x,y);ctx.restore()}
function ball(x,y,r,color){let g=ctx.createRadialGradient(x-r*.3,y-r*.35,r*.1,x,y,r);g.addColorStop(0,'#fff');g.addColorStop(.3,color);g.addColorStop(1,color);ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function project(a,scale,cx,cy,angle){let co=Math.cos(angle),si=Math.sin(angle);return {x:cx+(a.x*co+a.z*si)*scale,y:cy+a.y*scale,z:-a.x*si+a.z*co}}
function folded(cx,cy,scale,angle,alpha=1,gold=false){ctx.save();ctx.globalAlpha=alpha;let pts=residues.map(a=>project(a,scale,cx,cy,angle));let segs=[];for(let i=1;i<pts.length;i++)segs.push({a:pts[i-1],b:pts[i],z:(pts[i].z+pts[i-1].z)/2,i});segs.sort((a,b)=>a.z-b.z);for(let seg of segs){let c=gold?'#d3a443':colors[residues[seg.i].res]||'#58a6b8';line(seg.a,seg.b,'#2b536555',scale*.95);line(seg.a,seg.b,c,scale*.69);line({x:seg.a.x-1,y:seg.a.y-1},{x:seg.b.x-1,y:seg.b.y-1},'#ffffff66',scale*.16)}ctx.restore();return pts}
function polarDetail(){let atoms=byRes.get(24),ca=atoms.find(a=>a.name==='CA');let pts=atoms.map(a=>({x:1190+(a.x-ca.x)*15,y:172+(a.y-ca.y)*15,z:a.z,a}));for(let i=0;i<atoms.length;i++)for(let j=i+1;j<atoms.length;j++){let d=Math.hypot(atoms[i].x-atoms[j].x,atoms[i].y-atoms[j].y,atoms[i].z-atoms[j].z);if(d<1.9)line(pts[i],pts[j],'#12a391',3)}for(let p of pts){ball(p.x,p.y,6,p.a.element==='O'?'#e36883':p.a.element==='N'?'#4278e6':'#12a391');}label('Ser24 · polar –CH₂–OH',1190,114,'#078b7f',17);ctx.setLineDash([4,5]);line({x:1215,y:160},{x:1270,y:174},'#12a391',2);ctx.setLineDash([]);label('H₂O',1280,180,'#078b7f',17);label('can hydrogen-bond',1190,230,'#078b7f',16)}
function protease(cx,cy,scale,angle,kind){let data=kind==='pepsin'?PEPSIN:TRYPSIN;let pts=data.map(a=>project(a,scale,cx,cy,angle));for(let i=1;i<pts.length;i++){line(pts[i-1],pts[i],'#bd8428',scale*1.1);line({x:pts[i-1].x,y:pts[i-1].y-1},{x:pts[i].x,y:pts[i].y-1},'#ffe1a3',scale*.45)}}
function atomCloud(cx,cy,scale,angle,alpha=1,alteration=0){ctx.save();ctx.globalAlpha=alpha;let pts=MOLECULE.map(a=>({...project(a,scale,cx,cy,angle),a})).sort((a,b)=>a.z-b.z);for(let p of pts){let altered=alteration>0&&[35,52].includes(p.a.i)&&!['N','CA','C','O'].includes(p.a.name);ball(p.x+(altered?alteration*12:0),p.y-(altered?alteration*8:0),scale*(p.a.element==='S'?1.8:1.45),altered?'#b577c8':colors[p.a.res]||'#58a6b8')};ctx.restore()}
// A single backbone morphs from the known fold to an enlarged segment of its own sequence.
function backboneMorph(cx,cy,scale,angle,spread){let pts=residues.map((a,i)=>{let p=project(a,scale,cx,cy,angle);return {x:mix(p.x,700+(i-3.5)*132,spread),y:mix(p.y,390+13*Math.sin(i*Math.PI),spread),z:p.z}});let segs=[];for(let i=1;i<pts.length;i++)segs.push({i,a:pts[i-1],b:pts[i],z:pts[i].z});segs.sort((a,b)=>a.z-b.z);for(let q of segs){line(q.a,q.b,colors[residues[q.i].res]||'#58a6b8',mix(scale*.7,7,spread));line({x:q.a.x,y:q.a.y-2},{x:q.b.x,y:q.b.y-2},'#ffffff77',2)}}
const shortSeq=['LYS','VAL','PHE','GLY','ARG','CYS','GLU','LEU'];
// Chemical diagrams: repeating N–Cα–C(=O) backbone, true side-chain connectivity for four exemplars.
function chemicalChain(cx,cy,unit,unfold=1,cleavage=0,phase=0){let nodes=[];let n=8;let fragments=[];for(let i=0;i<n;i++){let group=cleavage>1.8?(i<4?i:4+Math.floor((i-4)/2)):cleavage>1?Math.floor(i/2):cleavage>0?Math.floor(i/4):0;let shift=cleavage*group*unit*.18;let x=cx+(i-3.5)*unit+shift,y=cy+Math.sin(i*.8+phase)*(22*(1-unfold)+4)+group*cleavage*18;let N={x:x-unit*.28,y:y+13},A={x,y},C={x:x+unit*.28,y:y+13},O={x:C.x,y:C.y+33};let color=colors[shortSeq[i]]||'#48a0ae';if(i>0){let broken=cleavage>1.8?(i<=4||i%2===0):cleavage>1?(i%2===0):cleavage>0?(i%4===0):false;if(!broken){line(nodes[i-1].C,N,'#324f67',5);if(!cleavage&&i===3){line(nodes[i-1].C,N,'#da8c2b',8);label('peptide bond',x-unit*.54,y+90,'#a35d11',18);line({x:x-unit*.55,y:y+68},{x:x-unit*.55,y:y+15},'#b37a30',1)}}}
line(N,A,'#45677c',4);line(A,C,'#45677c',4);line({x:C.x-3,y:C.y},{x:O.x-3,y:O.y},'#45677c',2);line({x:C.x+3,y:C.y},{x:O.x+3,y:O.y},'#45677c',2);ball(N.x,N.y,8,'#6e91da');ball(A.x,A.y,9,'#93a7b6');ball(C.x,C.y,8,'#93a7b6');ball(O.x,O.y,7,'#e47787');label('N',N.x,N.y+5,'#fff',13);label('O',O.x,O.y+4,'#fff',12);if(shortSeq[i]!=='GLY')line(A,{x,y:y-25},color,4);else label('H',x,y-21,'#546e7b',15);
let side=[];switch(shortSeq[i]){case 'LYS':side=[[0,-25],[16,-45],[0,-65],[16,-85],[0,-105]];break;case 'GLU':side=[[0,-25],[16,-45],[0,-65],[-18,-85],[0,-65],[18,-85]];break;case 'PHE':side=[[0,-25],[0,-45],[19,-56],[19,-78],[0,-89],[-19,-78],[-19,-56],[0,-45]];break;case 'SER':side=[[0,-25],[12,-49]];break;case 'VAL':side=[[0,-25],[-18,-45],[0,-25],[18,-45]];break;case 'ARG':side=[[0,-25],[16,-45],[0,-65],[16,-85],[0,-105],[-20,-120],[0,-105],[20,-120]];break;case 'CYS':side=[[0,-25],[12,-49]];break;case 'LEU':side=[[0,-25],[16,-45],[-2,-65],[16,-45],[34,-65]];break;case 'GLY':side=[];break;default:side=[[0,-25],[12,-45]]}
for(let j=1;j<side.length;j++)line({x:x+side[j-1][0],y:y+side[j-1][1]},{x:x+side[j][0],y:y+side[j][1]},color,3);
if(shortSeq[i]==='PHE'){ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y-67,12,0,Math.PI*2);ctx.stroke();}if(shortSeq[i]==='GLU'){line({x:x-4,y:y-65},{x:x-21,y:y-85},color,2);label('O',x-22,y-89,color,15);label(chapter===3&&t<242?'OH':'O⁻',x+23,y-86,color,15)}if(shortSeq[i]==='ARG'){label('NH',x+20,y-89,color,14);label('NH₂',x-28,y-124,color,14);label('NH₂⁺',x+31,y-124,color,14)}if(shortSeq[i]==='CYS')label('SH',x+14,y-56,color,17);if(shortSeq[i]==='LYS')label('NH₃⁺',x,y-112,color,17);if(shortSeq[i]==='SER')label('OH',x+14,y-56,color,17);
if(cleavage>0){let cutBefore=i>0&&((cleavage>1.8?(i<=4||i%2===0):(cleavage>1?i%2===0:i%4===0)));let cutAfter=i<7&&((cleavage>1.8?(i<4||(i+1)%2===0):(cleavage>1?(i+1)%2===0:(i+1)%4===0)));if(cutBefore)label('H',N.x-12,N.y-15,'#567183',13);if(cutAfter)label('OH',C.x+18,C.y+4,'#e47787',13);}label(shortSeq[i],x,y-145,color,18);nodes.push({N,A,C,O,color});fragments.push({x,y})}
return nodes}
function brace(x1,x2,y,text){line({x:x1,y:y-8},{x:x1,y},'#457889',2);line({x:x1,y},{x:x2,y},'#457889',2);line({x:x2,y},{x:x2,y:y-8},'#457889',2);label(text,(x1+x2)/2,y+26,'#376778',18)}
function draw(){if(innerWidth<800){let pan=document.querySelector('.canvas-window');let target=chapter<2&&t>23&&t<115?160+((t%60)/60)*580:350;if(playing)pan.scrollLeft=mix(pan.scrollLeft,target,.03);else if(pan.dataset.started!=='true'){pan.scrollLeft=350;pan.dataset.started='true';}}ctx.clearRect(0,0,1400,760);let s=sceneAt(t),local=t-starts[s],phase=$('motion').checked?0:t*.09;ctx.save();
if(s===0){let p=ease((local-10)/13);if(p<.2)atomCloud(700,355,10,phase*.14,1-ease(p/.2));if(p<1)backboneMorph(700,355,10,phase*.14,p);if(p>0){ctx.globalAlpha=ease((p-.6)/.4);chemicalChain(700,390,132,1,0,phase);brace(186,398,505,'dipeptide · 2 residues');brace(450,794,550,'tripeptide · 3 residues');label('Lysozyme residues 1–8 · the full polypeptide has 129 residues',700,617,'#355b73',24);ctx.globalAlpha=1}if(local<14){label('One protein. A specific amino-acid sequence.',700,612,'#24475f',25);label('129 amino acids · lysozyme in egg white',700,650,'#547286',19)}}
if(s===1){let fold=ease((local-48)/29.6);ctx.globalAlpha=1-fold;chemicalChain(700,395,132,1,0,phase);if(local<48){polarDetail();label(local<30.8?'Same core. Different side chains.':local<40.7?'Polar groups attract water; nonpolar groups avoid water.':'Opposite charges attract; like charges can repel.',700,585,'#355b73',23);if(local>40.7&&local<48){ctx.setLineDash([5,7]);line({x:238,y:278},{x:1031,y:292},'#9885ca',3);ctx.setLineDash([]);label('+',230,243,'#4278e6',30);label('−',1030,247,'#e36883',30)}}ctx.globalAlpha=1;if(fold>.8)atomCloud(700,355,10,phase*.12,ease((fold-.8)/.2));if(fold>0)backboneMorph(700,355,10,phase*.12,1-fold);if(fold>0){label('Side-chain chemistry influences the three-dimensional fold.',700,601,'#24475f',25);label('Conceptual compaction · not a simulated folding pathway',700,635,'#547286',18)}}
if(s===2){let angle=.65+Math.sin(phase*.12)*.15;atomCloud(665,355,11,angle,.9,ease((local-16.2)/9));folded(665,355,11,angle,.6);let dock=ease(local/14),change=ease((local-16.2)/9);let lx=mix(1120,810,dock)+change*100,ly=350-change*45; // Schematic carbohydrate chain in the lysozyme binding cleft.
ctx.save();ctx.strokeStyle='#de9c29';ctx.lineWidth=5;for(let i=0;i<3;i++){let x=lx+i*48,y=ly+Math.sin(i)*15;ctx.beginPath();for(let j=0;j<6;j++){let a=j*Math.PI/3;let xx=x+22*Math.cos(a),yy=y+22*Math.sin(a);j?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)}ctx.closePath();ctx.stroke();label('O',x+11,y-14,'#b97413',13);if(i>0)line({x:x-26,y},{x:x-48,y:ly+Math.sin(i-1)*15},'#de9c29',3)}ctx.restore();label('Sugar-chain fragment',lx+48,ly-63,'#ad6a10',19);line({x:850,y:498},{x:770,y:386},'#47788e',2);label(change>.5?'Hypothetical local change → poorer binding':'Substrate-binding cleft',900,522,'#24475f',23);label('A sequence change can alter chemistry, binding, or surface interactions.',700,602,'#24475f',24);if(local>34)label('Distinct example: sickle hemoglobin forms fibers under low oxygen.',700,638,'#547286',18)}
if(s===3){let entry=ease(local/12),zoom=ease((local-9)/10),duod=ease((local-50.8)/10);ctx.save();ctx.globalAlpha=entry;let ax=mix(500,230,duod),ay=116,aw=840; if(anatomy.complete&&anatomy.naturalWidth)ctx.drawImage(anatomy,ax,ay,aw,aw*anatomy.height/anatomy.width);ctx.restore();folded(mix(665,mix(745,1040,duod),entry),mix(355,385,entry),mix(11,1.1,entry),phase*.14,1-zoom);if(entry>.5){label('Stomach',mix(730,460,duod),200,'#5e7180',21);label('Pancreas',mix(1000,730,duod),500,'#087784',18);label('Duodenum',mix(1180,900,duod),620,'#5e7180',18)}
if(zoom>0){ctx.save();ctx.globalAlpha=zoom;ctx.fillStyle='#f5fafdEE';ctx.beginPath();ctx.roundRect(52,215,770,355,22);ctx.fill();ctx.strokeStyle='#c6dce5';ctx.lineWidth=2;ctx.stroke();let denat=ease((local-14)/14);let cleave=local<37.1?0:local<55?ease((local-37.1)/8):1+ease((local-55)/15);ctx.save();ctx.translate(437,400);ctx.scale(.58,.58);chemicalChain(0,0,132,denat,cleave,phase);ctx.restore();label(local<37.1?'HCl: structure loosens; peptide bonds remain':local<50.8?'Pepsin: peptide bonds are hydrolyzed':'Pancreatic + intestinal proteases: further hydrolysis',437,260,'#24475f',21);label(local<37.1?'DENATURATION ≠ HYDROLYSIS':local<50.8?'Shorter peptide chains':'Small peptides + free amino acids',437,540,'#087784',20);line({x:822,y:340},{x:mix(780,1040,duod),y:380},'#087784',2);
if(local>=37.1){let ex=270+Math.sin(phase*.8)*30;protease(ex,475,1.35,phase*.2,local<50.8?'pepsin':'trypsin');label(local<50.8?'Pepsin':'Protease',ex,514,'#a3650b',17);label('H₂O',ex+65,475,'#a3650b',17)}
ctx.restore()}if(local>69){label('The original food protein has been dismantled.',700,624,'#24475f',24)} }
if(s>=4)drawExtension(s,local,phase);
ctx.restore()}
function frame(now){let dt=Math.min((now-last)/1000,.12);last=now;if(playing){let before=t;let next=Math.min(720,t+dt*speed);let at=[180,274,604].find(v=>before<v&&next>=v&&!passed.has(v));if(at)showPrediction(at);else{t=next;if(t>=720){pause();$('status').textContent='Journey complete. Food supplies the amino acids; DNA supplies the instructions.'}update()}}draw();requestAnimationFrame(frame)}
update();requestAnimationFrame(frame);
// Deterministic QA hooks expose the existing timeline only, without altering product behavior.
window.journey={seek,getState:()=>({time:t,playing,scene:sceneAt(t),prediction:pausedAt}),draw};
